config/routes.rb
Tumblrtv::Application.routes.draw do

  root :to => 'home#index'
  get   "home/index" , :as => "home"
  match '/info/' =>'home#info' 
  match '/results/' =>'home#results' 
  match '/winner/:id' => 'home#winner'

  # Git hub oauth 
  match '/auth/github/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  # Login and logout 
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  # For managing join_requests 
  match '/join/:id' => 'join_requests#create', :as => 'join_team'
  match '/accept/:id' => 'join_requests#accept', :as => 'accept'
  match '/decline/:id'=> 'join_requests#decline', :as => 'decline'

  # for managing add_requests
  match '/add/:id' => 'add_requests#create', :as => 'add_request'
  match '/accept_add/:id' => 'add_requests#accept', :as => 'accept_add'
  match '/decline_add/:id'=> 'add_requests#destroy', :as => 'decline_add'
  match '/add_member2/'  => 'add_requests#add2', :as => 'add2'

  # User  leaves team
  match '/leave/:id'  => 'team_members#leave',  :as =>'leave_team'

  # api for team members 
  match '/api_members' => 'team_members#api_members', :as =>'get_members'

  #Admin 
  match '/admin/' =>'home#admin' 
  match '/checkin/' =>'home#checkin' 
  match '/team/checkin/:id' =>'teams#checkin'
  match '/judges/' =>'home#judges' 
  match '/announcement/' =>'home#announcement' 

  #FAQ
  match '/faq/' => 'home#faq'

  # REST methods
  resources :teams
  resources :users
  resources :team_members
  
end

app/views/partials/myteam/_add_members.html.erb
<%-if @my_team.member_count < 4 %>
<div class="modal hide" id="addMemberModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
      <h2>Candidates to invite</h2>
  </div>
  <div class="modal-body" style="overflow:scroll;height:550px;">
    <% if @candidates.length < 1%>
      <h3 style="padding-left:20px"> No members to add</h3>
    <% else %>
      <%= form_tag add2_path , :name => "add2_form", :id=>"add2_form",:class => "formset", :method => "post" %>
      <div class='control-group' style='margin-bottom:0'>
        <%= label_tag :add_members, nil, :class => "control-label" %>
        <div class="controls" style='margin-bottom: 10px'>
          <%= text_field_tag(:handle, nil, "placeholder" => "Type the Github handle of user ", :"data-provide"=>"typeahead", :"data-source" => @handles , :"data-rules"=> "required",  :"data-name" =>"handle", :class=> "validate") %>
          <p class="help-block"></p>
        </div>
      </div>
      <div class="input">
        <%= submit_tag "Add", :class => "btn" %>
      </div>
      <h3 class="space_top" style="align:center;">OR </h3>
      <% @candidates.each do |user| %>
        <div class="row-fluid space_top">
          <div class="span2 ">
            <img class="small-avatar " src="<%= user.avatar %>">
          </div>
          <div class="span4">
            <h3><%= user.name %></h3>
            <div>
              <a href='<%= add_request_path(user.id) %>' class="btn addReq">Add</a>
            </div>
          </div>
          <div class="span6">
            <a href='http://github.com/<%= user.handle %>'><h3><%= user.handle %></h3></a>
            <h3> <%= user.email %> </h3>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<%-end %>

app/views/partials/myteam/_add_req_list.html.erb
<%-if current_user and @add_reqs %>
<a class="btn" data-toggle="modal" href="#addReqModal" >Pending Requests <span class="notification"><%= @add_reqs.length %></span></a>

<div class="modal hide" id="addReqModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Accept to join a team or Decline</h3>
  </div>
  <div class="modal-body" style="overflow:scroll;">
    <% if @add_reqs.length < 1 %>
       <h3> You dont have requests from any team right now. You can join/create a team</h3>
    <% else %>
    <% @add_reqs.each do |req| %>
      <div class="row-fluid space_top">
        <div class="span2">
          <img class ="small-avatar" src="<%= @teams_index[req.team_id].image_url %>">
        </div>
        <div class="span5">
          <h3><%= req.team_name %></h3>
        </div>
        <div class="span5">
          <a href='<%= accept_add_path(req.team_id) %>' class="btn acceptTeamReq">Accept</a>
          <a href='<%= decline_add_path(req.team_id) %>' class="btn declineTeamReq">Decline</a>      
        </div>
      </div>
    <% end %>
   <% end %>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>
<%-end%>

app/views/partials/myteam/_create_team.html.erb

      <h3>Please complete with team information</h3>
      <%= form_tag teams_path , :name => "team_form", :id=>"team_form",:class => "formset", :method => "post" ,  :multipart => true do %>
    
        <div class="control-group">
          <%= label_tag :"Team Name", nil, :class => "control-label" %>
          <div class="controls">
            <%= text_field_tag(:name, nil, :class => "validate input-xlarge", :"data-rules" => "required|max_length[10]", :"data-display"=>"Team Name", "placeholder" => "Team name", :"data-name" =>"Team Name", :id=>"Team Name") %>
            <p class="help-block"></p>
          </div>
        </div>

        <div class="control-group">
          <%= label_tag :"Team Description", nil, :class => "control-label"%>
          <div class="controls">
          <%= text_area_tag(:desc, nil, :class => "validate input-xlarge",  :"data-rules" => "max_length[80]", :"data-name" =>"TeamDesc", :id=>"TeamDesc") %>
            <p class="help-block"></p>
          </div>
        </div>


        <div class='control-group' style='margin-bottom:0'>
          <div class="controls">
            <%= label_tag :"Team avatar", nil, :class => "control-label"%>
            <img class='avatar' src = "/assets/avatar_team.gif"><br>
            <%= file_field_tag :image, :class => "medium", :size => "30" %>
          </div>
        </div>

        <div class='backend control-group'>
          <p class="help-block"></p>
        </div>      

        <div class="clearfix">
          <div class="input">
            <%= submit_tag "Save", :class => "btn" %>
          </div>
        </div>
      <% end %>
  

app/views/partials/myteam/_dummy.html.erb
<div class="row-fluid">
  <div class="span6">
    <h1 style="padding:left:20px;"> About Teams </h1>
    <div class="row-fluid space_top">
      <div class="span9 offset1">
        <p>
          In order to get started the first thing you need to do is to sign in with your GitHub account.
          Once you are signed in you can either create a new team or request to join a team.
          If your team is not full, others can send you requests to join it.
          </p>
      </div>
      <div class="span2">
      </div>
    </div>
    <a href='/auth/github' class="btn btn-large btn-primary bw space_top">Get Started</a>
  </div>
  <div class="span6">
    <%- [0,1].each do |row| %>
      <div class = "row <%= row == 1 ? 'space_top' : '' %>">
        <%- [0, 1].each do |col| %>
          <div class="span4">
            <img class='avatar' src = "/assets/avatar_user.gif">
          </div>
        <%- end %>
      </div>
    <%-end%>
  </div>
</div>

app/views/partials/myteam/_edit_team.html.erb
<div class="control-group">
  <%= label_tag :"Team Name", nil, :class => "control-label" %>
  <%= @my_team.name %>
</div>
<%= form_tag team_path(@my_team) , :name => "team_form", :id=>"team_form",:class => "formset", :method => "put" ,  :multipart => true do %>
<div class="control-group">
  <%= label_tag :"Team Description", nil, :class => "control-label"%>
  <div class="controls">
  <%= text_area_tag(:desc, @my_team.desc, :class => " input-xlarge team_data",  :"data-rules" => "max_length[80]", :"data-name" =>"TeamDesc", :id=>"TeamDesc" ) %>
    <p class="help-block"></p>
  </div>
</div>

<div class="control-group">
  <%= label_tag :"GitHub Repo Link", nil, :class => "control-label" %>
  <div class="controls">
    <%= text_field_tag(:repo, @my_team.repo, :class => "input-xlarge team_data ", "placeholder" => "Github repo url") %>
  </div>
</div>

<div class="control-group">
  <%= label_tag :"Website Link", nil, :class => "control-label" %>
  <div class="controls">
    <%= text_field_tag(:site, @my_team.site, :class => "input-xlarge team_data","placeholder" => "Website url") %>
    <p class="help-block"></p>
  </div>
</div>

    <label>Team Logo</label>
<img class="team avatar" src= '<%= @my_team.image_url %>'>
<div class='control-group' style='margin-bottom:0'>
<div class="controls">
  <%= file_field_tag :image, :class => "medium", :size => "30" %>
 <p class="help-block"></p>
</div>
</div>

<div class='backend control-group'>
  <p class="help-block"></p>
</div>

<div class="clearfix">
  <div class="input">
    <%= submit_tag "Update", :class => "btn" %>
  </div>
</div>
<% end %>
<a href='<%= team_path(@my_team) %>' id="delete_team" class='btn btn-danger'>Delete team</a>

app/views/partials/myteam/_join_requests.html.erb
<a class="btn space_top" data-toggle="modal" href="#pendingJoinReqModal" >Pending Join Requests From Users  <span class="notification"><%= @requests.length %></span></a>

<div class="modal hide" id="pendingJoinReqModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Pending requests from users to join your team</h3>
  </div>
  <div class="modal-body" style="overflow:scroll;height:250px;">
    <%-if @requests.count > 0 %>
      <% if @my_team.member_count == 4 %> 
        You Cannot any members now as your team is full.
      <% end %> 
      <% @requests.each do |request| %>
      <div class="row-fluid space_top">
        <div class="span2">
          <img class="small-avatar" src ='<%= @members[request.user_id].avatar %>'>
        </div>
        <div class="span4">
          <h3><%= @members[request.user_id].name %></h3>
          <% if @my_team.member_count < 4 %> 
            <a href='<%= accept_path(request.user_id) %>' class='btn owner_decides'>Accept</a> 
          <% end %>
          <a href='<%= decline_path(request.user_id) %>' class='btn owner_decides'>Decline</a>
        </div>
        <div class="span6">
          <a href='http://github.com/<%= @members[request.user_id].handle %>'><h3><%= @members[request.user_id].handle %></h3></a>
          <h3> <%= @members[request.user_id].email %> </h3>
        </div>
      </div>
    <% end %>

    <%-else %>
      <p>There are no outstanding requests to join your team at this time.</p>
    <%-end%>
  
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>



app/views/partials/myteam/_members.html.erb
<div class="general members" id="a1">
  <h2>Team Members</h2>
  <% i = 0 %>
  <%- [0,1].each do |row| %>
    <div class = "row <%= row == 1 ? 'space_top' : '' %>">
      <%- [0, 1].each do |col| %>
          <% i= i+1 %>
          <div class="span4">
            <% if @team_members.length >= i %>
              <% member = @team_members[(2*row) + col] %>
              <div class="tmember">
                <% if @my_team.owner_id != member.user_id %>
                <span class="notification del"><a href='<%= team_member_path(member.user_id) %>' class="removeMember" style="color:white;">x</a></span>
                <% end %>
                <img class='avatar' src="<%= @members[member.user_id].avatar %>">
              </div>
              <center>
                <a href='<%= get_url(member.user_handle) %>'>
                <%= member.user_handle %></a>  
              </center>
            <% else %>
              <img class='avatar' src = "/assets/avatar_user.gif">
              <center><a class="btn btn-warning" data-toggle="modal" href="#addMemberModal" >Add Member</a></center>
            <% end %>
          </div>
        <%- end %>
    </div>
  <%-end%>
</div>

app/views/partials/myteam/_select_team.html.erb
<!-- Modal to display message after join request -->
<div class="modal hide" id="joinModal">
  <div class="modal-body">
    <p id="join_message"></p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>

<!-- Display teams to join  -->
<div style="height:500px;overflow:scroll;">    
  <% @teams.each do |team| %>
    <% if team.member_count < 4 %>
      <div class="row-fluid space_top">
        <div class="span3">    
          <img class ="small-avatar" src="<%= team.image_url %>">
        </div>
        <div class="span4">
          <h2><%= team.name %></h2>
          <%  if @requested_teams.include?(team.id) %>
           <span class="light space_top"> Request pending </span>
          <% else %>
            <a href= '<%= join_team_path(team) %>' class="btn selectTeam" style="margin-top:10px;"> Join </a>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/partials/myteam/_team_details.html.erb
<%if @my_team.owner_id == current_user.id %>
  <div class="hero-unit">
  <h1>Team: <%= @my_team.name %></h1>
    <p>You are the team owner of <strong><%= @my_team.name %></strong>. To be most successful in the #ContributingCode Sprint invite your friends to help you.</p>
  </div>
  <div class="row-fluid">
    <div class="span6">
      <%= render :partial => "partials/myteam/edit_team"%>
    </div>
    <div class="span6">
      <%= render :partial => "partials/myteam/members"%>
      <%= render :partial => "partials/myteam/join_requests"%>
      <%= render :partial => "partials/myteam/add_members"%>
    </div>
  </div>
<% else %>
    <div class="row-fluid">
      <div class="span6">
        <h1><%= @my_team.name %></h1>
        <p> <%= @my_team.desc %></p>
        <img class="avatar" src="<%= @my_team.image_url %>"><br><br>
        <a href='<%= leave_team_path(current_user.id) %>' class='btn btn-danger leaveTeam'>Leave team</a>
      </div>
      <div class="span6">
        <h2>Team Members</h2>
        <% i = 0 %>
        <%- [0,1].each do |row| %>
          <div class = "row <%= row == 1 ? 'space_top' : '' %>">
            <%- [0, 1].each do |col| %>
              <% i= i+1 %>
              <div class="span4">
                <% if @team_members.length >= i %>
                  <% member = @team_members[(2*row) + col] %>
                  <img class='avatar' src="<%= @members[member.user_id].avatar %>">
                  <center><a href='<%= get_url(member.user_handle) %>'><%= member.user_handle %></a></center>
                  <% else %>
                    <img class='avatar' src = "/assets/avatar_user.gif">
                  <% end %>
              </div>
            <%- end %>
          </div>
        <%-end%>
      </div>
    </div>
<% end %> 