config/routes.rb
Tumblrtv::Application.routes.draw do

  root :to => 'home#index'
  get   "home/index" , :as => "home"
  match '/info/' =>'home#info' 
  match '/results/' =>'home#results' 
  match '/winner/:id' => 'home#winner'

  # Git hub oauth 
  match '/auth/github/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  # Login and logout 
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  # For managing join_requests 
  match '/join/:id' => 'join_requests#create', :as => 'join_team'
  match '/accept/:id' => 'join_requests#accept', :as => 'accept'
  match '/decline/:id'=> 'join_requests#decline', :as => 'decline'

  # for managing add_requests
  match '/add/:id' => 'add_requests#create', :as => 'add_request'
  match '/accept_add/:id' => 'add_requests#accept', :as => 'accept_add'
  match '/decline_add/:id'=> 'add_requests#destroy', :as => 'decline_add'
  match '/add_member2/'  => 'add_requests#add2', :as => 'add2'

  # User  leaves team
  match '/leave/:id'  => 'team_members#leave',  :as =>'leave_team'

  # api for team members 
  match '/api_members' => 'team_members#api_members', :as =>'get_members'

  #Admin 
  match '/admin/' =>'home#admin' 
  match '/checkin/' =>'home#checkin' 
  match '/team/checkin/:id' =>'teams#checkin'
  match '/judges/' =>'home#judges' 
  match '/announcement/' =>'home#announcement' 

  #FAQ
  match '/faq/' => 'home#faq'

  # REST methods
  resources :teams
  resources :users
  resources :team_members
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :team_member
  has_many :join_requests
  has_many :add_requests
  has_one :owned_team, :foreign_key => 'owner_id', :class_name => 'Team'
  has_one :team, :through => :team_member
  
  
  validates_presence_of   :handle
  validates_presence_of   :email , :message => "Email required!"
  validates_uniqueness_of :handle
  validates_format_of     :email, :with => %r{.+@.+\..+}


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  # Create user only if registration form is complete
  def create
    redirect_to "/" if session[:auth].blank?
    auth = session[:auth]
    user = User.new 
    user.uid = auth["uid"]
    user.name = params[:name]
    user.email = params[:email] 
    user.handle = auth["extra"]["raw_info"]["login"]
    user.avatar = auth["extra"]["raw_info"]["avatar_url"]
    user.tee = params[:tee] if params[:tee].present?
    user.gender = params[:gender]  if params[:gender].present?
    user.transport = params[:transport] if params[:transport].present?
      if user.save
        Resque.enqueue(RegisterMailer, user.id)
        session[:user_id] = user.id
        redirect_to "/"
      else
        flash[:errors] = user.errors
        @name = params[:name]
        @email = params[:email]
        @teams = Team.all
        @users = User.all
        @members = @users.index_by(&:id)
        @avatar = auth["extra"]["raw_info"]["avatar_url"]
        @handle = auth["extra"]["raw_info"]["login"]
        render "home/index"
      end 
  end  

  def update
    if current_user
      current_user.name = params[:name] if params[:name].present?
      current_user.tee = params[:tee] if params[:tee].present?
      current_user.gender = params[:gender] if params[:gender].present?
      current_user.transport = params[:transport] if params[:transport].present?
      current_user.save
    end
    redirect_to "/"
  end 

end

app/views/users/_new.html.erb
<div class="modal hide" id="myModal" >
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Please Complete the form to finish the registration </h3>
  </div>
  <div class="modal-body">
    <%= form_tag users_path , :class => "formset",  :name => "register_form", :id=>"register_form", :method => "post" %>
    <div class="row-fluid">
      <div class="span8">
        <div class="control-group">
          <%= label_tag :FirstName, "Name", :class => "control-label blue" %>
          <div class="controls">
            <%= text_field_tag(:name,@name, :"data-rules"=> "required|max_length[16]",  :"data-name" =>"name", :class => "validate input-xlarge") %>
            <p class="help-block">Please fill out your full name.</p>
          </div>
        </div>

        <div class="control-group">
          <%= label_tag :Email, nil, :class => "control-label blue" %>
          <div class="controls">
            <%= text_field_tag(:email,@email, :class => "validate input-xlarge", :"data-rules"=> "required|valid_email", :"data-display"=>"Email", :"data-name" =>"email" ) %>
            <p class="help-block">Email will only be used for the sprint.</p>
          </div>
        </div>
      </div>
      <div class="span4">
        <div class="control-group">
          Github : <a class="small-avatar" href="http://github.com/<%= @handle %>" target="_blank"><%= @handle %></a>
          <div class="controls">
            <a href="http://github.com/<%= @handle %>" target="_blank"><img src='<%= @avatar %>'></a>
          </div>
        </div>
      </div>
    </div>
  
    <div class="row-fluid">
      <div class="span4">
        <div class="control-group">
          <div class="controls">
            <p class="blue"> Choose your Shirt size</p>
            <ul style="list-style-type: none;">
              <li><%= radio_button_tag(:tee, "S") %> S</li>
              <li><%= radio_button_tag(:tee, "M",:html=>{:checked=>true})%> M</li>
              <li><%= radio_button_tag(:tee, "L") %> L</li>
              <li><%= radio_button_tag(:tee, "XL") %> XL</li>
              <li><%= radio_button_tag(:tee, "XXL") %> XXL</li>
            </ul>
          </div>
        </div>
      </div>  
      <div class="span6">
          <div class="control-group">
          <div class="controls">
            <p class="blue">Gender</p>
            <ul style="list-style-type: none;"><li><%= radio_button_tag(:gender, "F") %> F</li>
            <li><%= radio_button_tag(:gender, "M",:html=>{:checked=>true})%> M</li></ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row-fluid">
      <p class="blue"> Choose your mode of transport</p>
        <ul style="list-style-type: none;">
          <li><%= radio_button_tag(:transport, "0") %> I need a shuttle to parcmerced intern housing</li>
          <li><%= radio_button_tag(:transport, "1")%> I need a shutle to the Caltrain station</li>
          <li><%= radio_button_tag(:transport, "2",:html=>{:checked=>true}) %> I do not need a shuttle</li>
          <li>* An email on shuttle service will be sent once registrations are over</li>
        </ul>
        
    </div>
  </div>
  <div class="modal-footer">
    <div class="clearfix">
      <div class="input">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
        <%= submit_tag "Register", :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/users/_registration_closed.html.erb
<div class="modal hide" id="myModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3> Sorry we missed you </h3>
  </div>
  <div class="modal-body">
     We have closed the registration. Please follow us @cfcodesprint.
     We will post if we open more slots.
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>

app/views/users/_update_info.html.erb
<div class="modal hide" id="transportModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Please fill up  the appropriate fields </h3>
  </div>
  <div class="modal-body">
    <%= form_tag user_path(current_user) , :class => "formset",  :name => "transport_form", :id=>"transport_form", :method => "put" %>
    <div class="row-fluid">
      <div class="span4">
        <div class="control-group">
          <div class="controls">
            <p class="blue"> Choose your Shirt size</p>
            <ul style="list-style-type: none;">
              <li><%= radio_button_tag(:tee, "S") %> S</li>
              <li><%= radio_button_tag(:tee, "M")%> M</li>
              <li><%= radio_button_tag(:tee, "L") %> L</li>
              <li><%= radio_button_tag(:tee, "XL") %> XL</li>
              <li><%= radio_button_tag(:tee, "XXL") %> XXL</li>
            </ul>
          </div>
        </div>
      </div>  
      <div class="span6">
          <div class="control-group">
          <div class="controls">
            <p class="blue">Gender</p>
            <ul style="list-style-type: none;"><li><%= radio_button_tag(:gender, "F") %> F</li>
            <li><%= radio_button_tag(:gender, "M")%> M</li></ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row-fluid">
      <p class="blue"> Choose your mode of transport</p>
      <ul style="list-style-type: none;">
        <li><%= radio_button_tag(:transport, "0") %> I need a shuttle to parcmerced intern housing</li>
        <li><%= radio_button_tag(:transport, "1")%> I need a shutle to the Caltrain station</li>
        <li><%= radio_button_tag(:transport, "2") %> I do not need a shuttle</li>
        <li>* An email on shuttle service will be sent once registrations are over</li>
      </ul>        
    </div>
  </div>
  <div class="modal-footer">
    <div class="clearfix">
      <div class="input">
        <%= submit_tag "Update", :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/users/_user_info.html.erb
<div class="modal hide" id="userModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Update profile</h3>
  </div>
  <div class="modal-body">
    <%= form_tag user_path(current_user) , :class => "formset",  :name => "user_info_form", :id=>"user_info_form", :method => "put" %>
      <div class="control-group">
          <%= label_tag :FirstName, "Name", :class => "control-label blue" %>
          <div class="controls">
            <%= text_field_tag(:name,current_user.name, :"data-rules"=> "required|max_length[16]",  :"data-name" =>"name", :class => "validate input-xlarge") %>
            <p class="help-block">Please fill out your full name.</p>
          </div>
      </div>
    <div class="row-fluid">
      <div class="span4">
        <div class="control-group">
          <div class="controls">
            <p class="blue"> Choose your Shirt size</p>
            <ul style="list-style-type: none;">
              <li><%= radio_button_tag(:tee, "S") %> S</li>
              <li><%= radio_button_tag(:tee, "M")%> M</li>
              <li><%= radio_button_tag(:tee, "L") %> L</li>
              <li><%= radio_button_tag(:tee, "XL") %> XL</li>
              <li><%= radio_button_tag(:tee, "XXL") %> XXL</li>
            </ul>
          </div>
        </div>
      </div>  
      <div class="span6">
          <div class="control-group">
          <div class="controls">
            <p class="blue">Gender</p>
            <ul style="list-style-type: none;"><li><%= radio_button_tag(:gender, "F") %> F</li>
            <li><%= radio_button_tag(:gender, "M")%> M</li></ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row-fluid">
      <p class="blue"> Choose your mode of transport</p>
      <ul style="list-style-type: none;">
        <li><%= radio_button_tag(:transport, "0") %> I need a shuttle to parcmerced intern housing</li>
        <li><%= radio_button_tag(:transport, "1")%> I need a shutle to the Caltrain station</li>
        <li><%= radio_button_tag(:transport, "2") %> I do not need a shuttle</li>
        <li>* An email on shuttle service will be sent once registrations are over</li>
      </ul>        
    </div>
    <h4>* You can change/set your profile picture on Github </h4>
  </div>
  <div class="modal-footer">
    <div class="clearfix">
      <div class="input">
        <%= submit_tag "Update", :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

<% content_for :js do %>
 tee = '<%= current_user.tee %>'
 gender = '<%= current_user.gender %>'
 transport = '<%= current_user.transport %>'
<% end %>